### ISSUE TITLE
Misconfigured SSL

### ISSUE THREAD

**Issue by rorymbyrne** [xdamman/tipbox#15]
![screen shot 2017-04-13 at 14 39 03](https://cloud.githubusercontent.com/assets/18581795/25006966/b768c524-2056-11e7-90e0-48f2335fda59.png)

**Comment by tgouverneur** [comment]
Looks like the certificate was about to expire and causing issues with some browser although it's still valid. I'm renewing it now!

**Comment by tgouverneur** [comment]
Looks like startcom roots have been revoked on a lot of browser so I need to find another certificate issuer, I'll setup let's encrypt this evening and hopefully get all this resolved..

**Comment by tgouverneur** [comment]
There we go, tipbox.is now use let's encrypt certificate which will auto renew every 60 days.
Closing.
